// <auto-generated />
using System;
using ConexaoApp.FirmRegistry.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConexaoApp.FirmRegistry.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240504190404_DBEmpresa")]
    partial class DBEmpresa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Billing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Database")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("EmpresaId1")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Free")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId1");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Empresa", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abertura")
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSituacao")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSituacaoEspecial")
                        .HasColumnType("longtext");

                    b.Property<string>("Efr")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoSituacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .HasColumnType("longtext");

                    b.Property<string>("Situacao")
                        .HasColumnType("longtext");

                    b.Property<string>("SituacaoEspecial")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.Property<string>("UltimaAtualizacao")
                        .HasColumnType("longtext");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Extra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("EmpresaId1")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId1");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Qsa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("EmpresaId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Qual")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId1");

                    b.ToTable("Qsas");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Billing", b =>
                {
                    b.HasOne("ConexaoApp.FirmRegistry.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId1");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Extra", b =>
                {
                    b.HasOne("ConexaoApp.FirmRegistry.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId1");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ConexaoApp.FirmRegistry.Models.Qsa", b =>
                {
                    b.HasOne("ConexaoApp.FirmRegistry.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId1");

                    b.Navigation("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
